# Generated by Django 3.0.14 on 2022-05-05 14:36

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0012_policyrenewaldetail'),
        ('core', '0015_missing_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiueInsuree',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='niueInsureeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='niueInsureeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('birth_register_entry_number', models.CharField(db_column='birthRegisterEntryNumber', max_length=36, unique=True)),
                ('date_of_registration', core.fields.DateField(db_column='dateOfRegistration', default=datetime.datetime.now)),
                ('father_first_name', models.CharField(db_column='fatherFirstName', max_length=36)),
                ('father_last_name', models.CharField(db_column='fatherLastName', max_length=36)),
                ('father_residency_status', models.CharField(db_column='fatherResidencyStatus', max_length=36)),
                ('mother_first_name', models.CharField(db_column='motherFirstName', max_length=36)),
                ('mother_last_name', models.CharField(db_column='motherLastName', max_length=36)),
                ('mother_residency_status', models.CharField(db_column='motherResidencyStatus', max_length=36)),
                ('applicant_relationship_to_the_child', models.CharField(db_column='applicantRelationshipChild', max_length=36)),
                ('proof_of_permanent_resident', models.CharField(db_column='proofOfPermanentResident', max_length=255)),
                ('proof_of_identity', models.CharField(db_column='proofOfIdentity', max_length=36)),
                ('niuean_descendant', models.CharField(db_column='niueanDescendant', max_length=36)),
                ('New_zealand_citizen', models.CharField(db_column='newZealandCitizen', max_length=36)),
                ('obtained_permanent_resident_status', models.CharField(db_column='permanentResidentStatus', max_length=36)),
                ('Attached_certificate', models.CharField(db_column='attachedCertificate', max_length=36)),
                ('receive_pension_payments', models.CharField(db_column='receivePensionPayments', max_length=36)),
                ('copy_of_passport', models.CharField(db_column='copyOfPassoprt', max_length=36)),
                ('copy_of_permanent_residence_certificate', models.CharField(db_column='copyOfPermanentResidenceCert', max_length=36)),
                ('nationality', models.CharField(db_column='nationality', max_length=36)),
                ('citizenship', models.CharField(db_column='citizenship', max_length=36)),
                ('reason_for_applying_welfare_benefit', models.CharField(db_column='welfareBenefitReason', max_length=255)),
                ('dependency_children', models.CharField(db_column='childrenDependency', max_length=5)),
                ('dependency_relative', models.CharField(db_column='relativeDependency', max_length=5)),
                ('Person_take_care_applicant', models.CharField(db_column='personToTakeCareApplicant', max_length=36)),
                ('receive_any_support_at_all', models.CharField(db_column='receiveSupport', max_length=36)),
                ('receive_money_from_any_source', models.CharField(db_column='receiveMoney', max_length=36)),
                ('employed', models.CharField(db_column='employed', max_length=36)),
                ('weekly_wage', models.CharField(db_column='weekly_wage', max_length=36)),
                ('employment_for_you', models.CharField(db_column='employmentFoundForYou', max_length=36)),
                ('if_NO_Why', models.CharField(db_column='whyNoEmploymentIfFound', max_length=36)),
                ('cash_assets', models.CharField(db_column='cashAssets', max_length=36)),
                ('Debts_owing', models.CharField(db_column='debtsOwing', max_length=36)),
                ('interest_in_property', models.CharField(db_column='interestInProperty', max_length=36)),
                ('own_following_household_items', models.CharField(db_column='ownFollowingHouseholdItems', max_length=36)),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.Insuree')),
            ],
            options={
                'db_table': 'tblNiueInsurees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NiueInsureeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='niueinsuree', to='core.MutationLog')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='niue_insuree.NiueInsuree')),
            ],
            options={
                'db_table': 'niueInsureeMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
