# Generated by Django 3.0.14 on 2022-05-05 16:40

import core.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niue_insuree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niueinsureemutation',
            old_name='scheme',
            new_name='niueInsuree',
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='Attached_certificate',
            field=models.CharField(db_column='attachedCertificate', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='Debts_owing',
            field=models.CharField(db_column='debtsOwing', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='New_zealand_citizen',
            field=models.CharField(db_column='newZealandCitizen', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='Person_take_care_applicant',
            field=models.CharField(db_column='personToTakeCareApplicant', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='applicant_relationship_to_the_child',
            field=models.CharField(db_column='applicantRelationshipChild', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='birth_register_entry_number',
            field=models.CharField(db_column='birthRegisterEntryNumber', max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='cash_assets',
            field=models.CharField(db_column='cashAssets', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='citizenship',
            field=models.CharField(db_column='citizenship', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='copy_of_passport',
            field=models.CharField(db_column='copyOfPassoprt', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='copy_of_permanent_residence_certificate',
            field=models.CharField(db_column='copyOfPermanentResidenceCert', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='date_of_registration',
            field=core.fields.DateField(db_column='dateOfRegistration', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='dependency_children',
            field=models.CharField(db_column='childrenDependency', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='employed',
            field=models.CharField(db_column='employed', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='employment_for_you',
            field=models.CharField(db_column='employmentFoundForYou', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='father_first_name',
            field=models.CharField(db_column='fatherFirstName', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='father_last_name',
            field=models.CharField(db_column='fatherLastName', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='father_residency_status',
            field=models.CharField(db_column='fatherResidencyStatus', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='if_NO_Why',
            field=models.CharField(db_column='whyNoEmploymentIfFound', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='interest_in_property',
            field=models.CharField(db_column='interestInProperty', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='mother_first_name',
            field=models.CharField(db_column='motherFirstName', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='mother_last_name',
            field=models.CharField(db_column='motherLastName', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='mother_residency_status',
            field=models.CharField(db_column='motherResidencyStatus', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='nationality',
            field=models.CharField(db_column='nationality', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='niuean_descendant',
            field=models.CharField(db_column='niueanDescendant', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='obtained_permanent_resident_status',
            field=models.CharField(db_column='permanentResidentStatus', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='own_following_household_items',
            field=models.CharField(db_column='ownFollowingHouseholdItems', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='proof_of_identity',
            field=models.CharField(db_column='proofOfIdentity', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='proof_of_permanent_resident',
            field=models.CharField(db_column='proofOfPermanentResident', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='reason_for_applying_welfare_benefit',
            field=models.CharField(db_column='welfareBenefitReason', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='receive_any_support_at_all',
            field=models.CharField(db_column='receiveSupport', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='receive_money_from_any_source',
            field=models.CharField(db_column='receiveMoney', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='niueinsuree',
            name='receive_pension_payments',
            field=models.CharField(db_column='receivePensionPayments', max_length=36, null=True),
        ),
    ]
