# Generated by Django 3.0.14 on 2022-05-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20220427_1337'),
        ('niue_insuree', '0003_auto_20220506_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='niueinsuree',
            name='banks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='banks.Bank'),
        ),
    ]
