# Generated by Django 3.0.14 on 2022-05-23 15:27

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niue_insuree', '0004_niueinsuree_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='niueinsuree',
            name='applicant_DOB',
            field=core.fields.DateField(blank=True, db_column='applicantDOB', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='niueinsuree',
            name='applicant_first_name',
            field=models.CharField(blank=True, db_column='applicantFirstName', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='niueinsuree',
            name='applicant_last_name',
            field=models.CharField(blank=True, db_column='applicantLastName', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='niueinsuree',
            name='bank_number',
            field=models.CharField(blank=True, db_column='bankNumber', max_length=36, null=True),
        ),
    ]
