# Generated by Django 3.0.14 on 2022-05-23 16:53

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niue_insuree', '0005_auto_20220523_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='niueinsuree',
            name='tin_no',
            field=core.fields.DateField(blank=True, db_column='tinNo', max_length=36, null=True),
        ),
    ]
