# Generated by Django 3.0.14 on 2022-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niue_insuree', '0006_niueinsuree_tin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niueinsuree',
            name='tin_no',
            field=models.CharField(blank=True, db_column='tinNo', max_length=36, null=True),
        ),
    ]
