# Generated by Django 3.0.14 on 2022-04-26 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(db_column='bankID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='bankUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('bank_name', models.CharField(db_column='bank_name', max_length=250)),
                ('bannk_account_number', models.IntegerField(db_column='bank_account_number')),
            ],
        ),
    ]
