# Generated by Django 3.0.14 on 2022-04-26 14:06

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_missing_roles'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='bank',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_column='LegacyID', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bank',
            name='validity_to',
            field=core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True),
        ),
        migrations.AlterModelTable(
            name='bank',
            table='tblBanks',
        ),
        migrations.CreateModel(
            name='BankMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='banks.Bank')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Bank', to='core.MutationLog')),
            ],
            options={
                'db_table': 'BankMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
