# Generated by Django 3.0.14 on 2022-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20220426_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_address',
            field=models.CharField(db_column='bank_address', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_contact_detail',
            field=models.IntegerField(db_column='bank_contact_detail', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_email',
            field=models.EmailField(db_column='bank_email', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_switch_code',
            field=models.IntegerField(db_column='switch_code', null=True),
        ),
    ]
