# Generated by Django 3.0.14 on 2022-03-08 14:54

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_missing_roles'),
        ('insuree', '0012_policyrenewaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='programsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.Insuree')),
            ],
            options={
                'db_table': 'tblPrograms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SchemeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='schemeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('start_date', core.fields.DateField(db_column='StartDate')),
                ('end_date', core.fields.DateField(db_column='EndDate')),
                ('code', models.CharField(db_column='code', max_length=15, unique=True)),
                ('created_at', core.fields.DateField(db_column='CreatedAt', default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='Status', default='active', max_length=255)),
                ('scheme_type', models.CharField(choices=[('cash', 'Cash'), ('in-kind', 'In-kind'), ('cash-in-kind', 'Cash & In-Kind')], db_column='SchemeType', default='cash', max_length=255)),
                ('amount', models.DecimalField(db_column='AmountPaid', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'tblSchemes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='insureee',
            fields=[
            ],
            options={
                'db_table': 'tblInsuree',
                'ordering': ('id',),
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insuree.insuree',),
        ),
        migrations.CreateModel(
            name='SchemeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheme', to='core.MutationLog')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='programs.Scheme')),
            ],
            options={
                'db_table': 'schemeMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.CreateModel(
            name='ProgramsMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='core.MutationLog')),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='programs.Programs')),
            ],
            options={
                'db_table': 'programsMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.AddField(
            model_name='programs',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programs.Scheme'),
        ),
    ]
