# Generated by Django 3.0.14 on 2022-04-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='insureee',
        ),
    ]
