# Generated by Django 3.0.14 on 2022-05-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0012_policyrenewaldetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
    ]
