# Generated by Django 3.0.14 on 2022-05-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20220526_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': False},
        ),
    ]
