# Generated by Django 3.0.14 on 2022-03-08 15:11

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_missing_roles'),
        ('insuree', '0012_policyrenewaldetail'),
        ('payrollcycle', '0001_initial'),
        ('service_provider', '0001_initial'),
        ('location', '0006_users_api'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PaymentDetailsID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PaymentDetailsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('expectedamount', models.DecimalField(db_column='ExpectedAmount', decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(blank=True, db_column='AmountPaid', decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.CharField(db_column='StartDate', max_length=10)),
                ('end_date', models.CharField(db_column='EndDate', max_length=10)),
                ('location_type', models.CharField(blank=True, choices=[('R', 'Region'), ('D', 'District'), ('W', 'Ward'), ('V', 'Settlement'), ('P', 'Paypoint')], db_column='LocationType', max_length=1, null=True)),
                ('rundate', models.DateField(blank=True, db_column='RunDate', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserId', null=True)),
                ('is_approved', models.BooleanField(db_column='IsApproved', default=False)),
                ('approved_by_id', models.IntegerField(blank=True, db_column='ApprovedBy', null=True)),
                ('transaction_number', models.CharField(blank=True, db_column='TransactionNumber', max_length=25, null=True)),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.Insuree')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.Location')),
                ('payrollcycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payrollcycle.PayrollCycle')),
                ('psp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_provider.ServiceProvider')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programs.Scheme')),
            ],
            options={
                'db_table': 'tblPayroll',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentDetails',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PaymentDetailsID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PaymentDetailsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('transaction_number', models.CharField(db_column='TransactionNumber', max_length=25)),
                ('payment_status', models.BooleanField(db_column='PaymentStatus', default=False)),
                ('received_amount', models.DecimalField(db_column='ReceivedAmount', decimal_places=2, default=0.0, max_digits=12)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('receipt_number', models.CharField(blank=True, db_column='ReceiptNumber', max_length=24, null=True)),
                ('type_of_payment', models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('transfer', 'Transfer'), ('kind', 'kind'), ('others', 'Others')], db_column='TypeOfPayment', max_length=12, null=True)),
                ('transfer_fee', models.DecimalField(blank=True, db_column='TransferFee', decimal_places=2, max_digits=12, null=True)),
                ('reasons_for_not_paid', models.CharField(blank=True, db_column='ReasonsForNotPaid', max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, db_column='ReceiverName', max_length=100, null=True)),
                ('identification_number', models.CharField(blank=True, db_column='IdentificationNumber', max_length=25, null=True)),
                ('receiver_phone_number', models.CharField(blank=True, db_column='ReceiverPhoneNumber', max_length=25, null=True)),
                ('identification_type', models.ForeignKey(blank=True, db_column='IdentificationType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.IdentificationType')),
                ('paypoint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_provider.Paypoint')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.Payroll')),
                ('psp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_provider.ServiceProvider')),
            ],
            options={
                'db_table': 'tblPayrollPaymentDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentDetailsMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PayrollPaymentDetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='payroll.PayrollPaymentDetails')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payrollPaymentDetails', to='core.MutationLog')),
            ],
            options={
                'db_table': 'payroll_PayrollPaymentDetailsMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.CreateModel(
            name='PayrollMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Payroll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='payroll.Payroll')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll', to='core.MutationLog')),
            ],
            options={
                'db_table': 'payroll_PayrollMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
